# Generated by Django 3.2.7 on 2022-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Modern'), ('A', 'Abstract'), ('R', 'Realistic')], max_length=2),
        ),
    ]
