# Generated by Django 3.2.7 on 2022-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Modern'), ('A', 'Abstract'), ('R', 'Realistic'), ('B', 'Blood_paintins')], max_length=2),
        ),
    ]
